<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>mac</string>
		<string>hea</string>
	</array>
	<key>name</key>
	<string>6502/65816 Assembly (MADS)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#6502</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#65816</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#macros</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quotes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#external</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#misc</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#labels</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)((^|\s+)\.error|\s+ert)\b</string>
					<key>name</key>
					<string>keyword.control.error</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)((^|\s+)(\.en)|^(\s+|\S+\s+)(end))\b</string>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.end</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.end</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)((^|\s+)(\.(if|ifdef|ifndef)|#(if|while))|\s+ift|^\s+(eli|els|eif)|^\s*(\.(else|elseif|endif)|#(else|end)))\b</string>
					<key>name</key>
					<string>keyword.control.if</string>
				</dict>
			</array>
		</dict>
		<key>6502</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(\s+|(?<=:))(adc|and|asl|bcc|bcs|beq|bit|bmi|bne|bpl|brk|bvc|bvs|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|jmp|jsr|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|rti|rts|sbc|sec|sed|sei|sta|stx|sty|tax|tay|tsx|txa|txs|tya)(?=\.[bzwaqlt]|\s+|[:$#(\\])</string>
					<key>name</key>
					<string>keyword.other.opcode.6502.legal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(\s+|(?<=:))(aso|rln|lse|rrd|sax|lax|dcp|isb|anc|alr|arr|ane|anx|sbx|las|sha|shs|shx|shy|npo|cim|dop|top)(?=\s+|[:$#(])</string>
					<key>name</key>
					<string>keyword.other.opcode.6502.illegal</string>
				</dict>
			</array>
		</dict>
		<key>65816</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(\s+|(?<=:))(stz|sep|rep|trb|tsb|bra|cop|mvn|mvp|pea|phb|phd|phk|phx|phy|plb|pld|plx|ply|rtl|stp|tcd|tcs|tdc|tsc|txy|tyx|wai|wdm|xba|xce|ina|dea|brl|jsl|jml)(?=\.[bzwaqlt]|\s+|[:$#(\\])</string>
					<key>name</key>
					<string>keyword.other.opcode.65816.legal</string>
				</dict>
			</array>
		</dict>
		<key>macros</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(\s+|(?<=:))(req|rne|rpl|rmi|rcc|rcs|rvc|rvs|seq|sne|spl|smi|scc|scs|svc|svs|jeq|jne|jpl|jmi|jcc|jcs|jvc|jvs|add|sub|adb|sbb|adw|sbw|phr|plr|inw|inl|ind|dew|del|ded|mva|mvx|mvy|mwa|mwx|mwy|cpb|cpw|cpl|cpd)(?=\s+|[:$#(])</string>
					<key>name</key>
					<string>keyword.other.opcode.macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(^|\s+)\.(macro|endm|mend|rept|endr|proc|endp|pend)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(^|\s+)\.(exitm|exit)\b</string>
					<key>name</key>
					<string>keyword.control.end</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
				<dict>
					<key>match</key>
					<string>//.*</string>
					<key>name</key>
					<string>comment.line.double-slash</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;.*</string>
					<key>name</key>
					<string>comment.line.semicolon</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\S*\s*(\*.*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.asterisk</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>quotes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(?<=,)\s*[xy]\b(?!.*\.reg)</string>
					<key>name</key>
					<string>constant.language.registers</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.decimal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\$\b\h+\b|\b0x\h+\b</string>
					<key>name</key>
					<string>constant.numeric.hexadecimal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%\b[0-1]+\b</string>
					<key>name</key>
					<string>constant.numeric.binary</string>
				</dict>
			</array>
		</dict>
		<key>storage</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\s+dta|((^|\s+|(?<=\())\.(d?byte|d?word|long)|(^|\s+)\.((zp)?var|reg|db|dw|by|ds|sb|cb|wo|he|fl))\b</string>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(^|\s+)\.(struct|ends|send|end|enum|ende|eend|array|enda|aend)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.struct</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(^|\s+)\.align\b</string>
					<key>name</key>
					<string>storage.modifier</string>
				</dict>
			</array>
		</dict>
		<key>labels</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(\bset|\.(adr|len|sizeof|filesize|def))\b</string>
					<key>name</key>
					<string>keyword.other.label.functions</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(^|\s+)\.(local|endl|lend)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.local</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)^\s*\.(using|use)\b</string>
					<key>name</key>
					<string>keyword.other.label.scope</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\w@][\w@?]*\.[\w@][\w@?]*</string>
					<key>name</key>
					<string>entity.name.other.label.scope</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^@(?=\s+)</string>
					<key>name</key>
					<string>entity.name.other.label.anonymous</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\w@][\w@?]*:?</string>
					<key>name</key>
					<string>entity.name.other.label.local</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s+(?<=:)[\w@][\w@?]*</string>
					<key>name</key>
					<string>entity.name.other.label.global</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?[\w@?]*</string>
					<key>name</key>
					<string>entity.name.other.label.temporary</string>
				</dict>
			</array>
		</dict>
		<key>misc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\s+opt\b</string>
					<key>name</key>
					<string>keyword.other.options</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\s+org\b</string>
					<key>name</key>
					<string>keyword.other.mem.new</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)^\s*\.segdef\b</string>
					<key>name</key>
					<string>keyword.other.mem.seg</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)^\s*\.(pages|endpg|pgend|segment|endseg)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.mem.seg</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(\s+(ins|icl)|(^|\s+)\.([wldx]?get|put|sav|link))\b</string>
					<key>name</key>
					<string>keyword.other.ram.load</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(sin|rnd)(?=\()\b</string>
					<key>name</key>
					<string>keyword.other.functions</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(^\s*\.(print|echo)|(^|\s+)\.nowarn)\b</string>
					<key>name</key>
					<string>keyword.other.debug</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\s+[lnr]mb\b</string>
					<key>name</key>
					<string>keyword.other.ram.bank</string>
				</dict>

			</array>
		</dict>
		<key>external</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(\s+(blk|smb|run|ini)|(^\s*)\.symbol)\b</string>
					<key>name</key>
					<string>keyword.other.dos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(^\s*)\.reloc\b</string>
					<key>name</key>
					<string>keyword.other.reloc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)((^\S+\s+(ext))|(^|\s+)(\.(extrn|public|global|globl)))\b</string>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.symbols</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.symbols</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)[+\-*/%!|^=~\:&amp;&lt;&gt;]|equ|\.(and|x?or|not|(lo|hi)(?=\s*\())</string>
					<key>name</key>
					<string>keyword.operators</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.asm.6502_65816.mads</string>
	<key>uuid</key>
	<string>8D1E7063-570E-4E88-AF2E-EA3CE330B2D3</string>
</dict>
</plist>
